name: MUX CI
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - run: unset VERILATOR_ROOT && verilator -Wall --binary --trace mux.v tb.v
      - run: ./obj_dir/Vmux
